version: '3.8'
services:

  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /apptron/front/node_modules:/app/front/node_modules
    stdin_open: true
    tty: true